### ISSUE TITLE
Questions regarding State sharing 

### ISSUE THREAD

**Issue by yairEO** [gunn/pure-store#5]
README doesn't show how the *state* can be accessed by child components,
For example a child component changes the state and the parent updates accordingly.

Also, it is unclear what is the API one can use in `pure-store` and also unclear if the state is component-specific or can be defined once (somehwere) and shared everywhere

**Comment by gunn** [comment]
Hi @yairEO, thanks for the question, the README badly needs to state this.

`pure-store` is very flexible with how it can be used. Once you have created a store you should use it's `subscribe` method to re-render e.g.:

``` javascript
const render = ()=> {
  ReactDOM.render(<App />, document.getElementById('root'))
}

store.subscribe(render)
render()
```

Then, when a child changes the state, the whole tree will update. You can either pass the store around, and access it's state from each component, or you can pass down pieces of the state as props. Or any combination.

Because the state object is immutable, if you pass down pieces of the state as props, you can use `React.PureComponent` to automatically only re-render when needed.

Until the README is updated, you can figure out `pure-store` by looking at the rather simple [source](https://github.com/gunn/pure-store/blob/master/src/index.ts) and [tests](https://github.com/gunn/pure-store/blob/master/src/index.test.ts). The only API methods not mentioned yet are `storeFor` and `updaterFor`. They let you define a subset of the store as a shortcut, so you don't have to reference the whole chain every time. E.g.:

```javascript
store.update(s=> s.user.profile.address.city = "Wellington")
// vs
const addressUpdater = store.updaterFor(s=> s.user.profile.address)
addressUpdater(a=> a.city = "Wellington")
```
Which could be useful in some larger projects.

**Comment by yairEO** [comment]
Thanks!

in the [test](https://github.com/gunn/pure-store/blob/master/src/index.test.ts) you wrote:

    interface State {...

I've never seen the `interface` keyword before and Googling it finds no relevant information. 
what is it?

**Comment by gunn** [comment]
@yairEO I mean just import the store into whatever file you want to use it in. You can also pass it, or fractions of the state by props.

The `interface` keyword is from from typescript - https://www.typescriptlang.org/docs/handbook/interfaces.html

It's not necessary to use typescript, but if you do`pure-store` supports it very well.

Updating the README is what I'm doing right now.

**Comment by yairEO** [comment]
You da man. keep up the good work!
