### ISSUE TITLE
[enhancement] Subscribe to multiple stores : Introducing withStores HOC 

### ISSUE THREAD

**Issue by shivekkhurana** [gunn/pure-store#8]
After having and issue #7 and seeing a similar issue #5, #4 , I have created a `withStores` HOC. 

```javascript
const withStores = (stores, WrappedComponent) => {
  class WithStoreHOC extends React.Component {
    constructor(props) {
      super(props)
      this.unsubscribeFunctions = stores.map(store => 
        store.subscribe(()=> this.forceUpdate())
      )
    }
    componentWillUnmount() {
      this.unsubscribeFunctions.map(
        unsubscribeFunction => unsubscribeFunction()
      )
    }
    render() {
      return (<WrappedComponent />);
    }
  }
    
  return WithStoreHOC;
};

export default withStores;
```

It can be used like : 

```javascript
const store = createStore({
  count: 0
}); 

const localStore = createStore({
  count: 0
}); 


const Counter = () => {
  return (<div>
    Counter
    <div>Store {store.state.count}</div>
    <div>Local Store {localStore.state.localCount}</div>
    <div>
      <a onClick={() => store.update(s => s.count++)}>Plus</a>
      <a onClick={() => localStore.update(s => s.localCount--)}>Minus</a>
    </div>
  </div>);
};

const ReactiveCounter = withStores([store, localStore], Counter);
```

This technically makes pure-store reactive. Not sure about abouthow the performance compares with Redux or others, but certainly gives a more pleasant api. I'm gonna use this for a smaller application and see how it goes. 

PS: I wanted to raise a PR to merge this to upstream, but I realised that my typescript foo is not very strong. Also, adding an HOC introduces React as a peer dependancy. 

@gunn If you want, you can add this to pure-store. Or maybe create a `react-pure-store` package to expose this HOC. I don't mind creating that package if you want me to do it, but something coming from the original author adds more credibility. 

Update 0: 
After checking react docs for [forceUpdate](https://reactjs.org/docs/react-component.html#forceupdate), that say:
> React will still only update the DOM if the markup changes. 

I feel that this will not cause any significant performance issues. Although render is called each time the store changes, the actual DOM is not updated till a mutation occurs. 

A better way however will be to pass down store state as a prop.

**Comment by gunn** [comment]
Hey @shivekkhurana, yes this will certainly work. It wouldn't be my choice though because of the performance reasons you point out which could add up in situations with long lists, and because I want to avoid boilerplate code.

The style I recommend is to trigger a re-render of your base component either with a `forceUpdate` call, or like this:

```javascript
const render = ()=> {
  ReactDOM.render(<App />, document.getElementById('root'))
}

store.subscribe(render)
render()
```

if you pass down the pieces of the store's state needed by each component as props, then you can make use of `React.PureComponent` to be very efficient.

P.S. I've just updated https://github.com/gunn/pure-store/blob/master/README.md with this advice and more.

**Comment by gunn** [comment]
Yes, and it will be nicer than `mapStateToProps` since there's no extra boilerplate, and no extra thinking required - just pass whatever piece of state as a prop for a pure component, and immutability does the rest.

No, there will be no issue with multiple stores, just make sure you have a subscribe callback that triggers re-rendering. If one of the stores was used for only part of the component tree, you could use a `forceUpdate` on the root component of that tree. I do wonder why you would want multiple stores though? maybe a [sub-store](https://github.com/gunn/pure-store#bonus-storeforgetter--updaterforgetter) would be just as good?

Regarding the two re-rendering approaches, the two are the same: `forceUpdate` still runs the render method, it just doesn't update the DOM if there was no difference. This is how all of react and most if not all virtual-dom libraries work.

**Comment by shivekkhurana** [comment]
Re: mapStateToProps
I don't get it. I was referring to an HOC similar to redux's `mapStateToProps`. I was in favour of replicating the same for pure-store.

Are you suggesting the use of PureComponents along with root `store.subscribe(render)` ?

Re: Multiple stores
I come from the clojure world and am trying to think of store as an [atom](https://clojuredocs.org/clojure.core/atom). In simple terms, an immutable data structure. 

With multiple stores, I can fine tune re-rendering. I don't think the slowness of a single store/ root node re-render will be evident until after 200 components (rough guess based on gut feelings and no empirical evidence). 

Re: Two re-render approaches
With the forceUpdate HOC, only a subtree will be re-rendered. With root `store.subscribe(render)` the entire app will be re-rendered. I still fail to understand why are the approaches identical.

**Comment by shivekkhurana** [comment]
It's also worth checking the [HOC implementation](https://github.com/taviroquai/ReactObservableStore/blob/master/src/ObserverComponent.js) for [ReactObservableStore](https://github.com/taviroquai/ReactObservableStore). 

It uses `setState` to change the state when the store changes. And render just passes the state down as props to the wrapped component.

**Comment by gunn** [comment]
I was suggesting a HOC probably isn't needed, and yes to use PureComponents along with re-rendering from the root. However if you want to go clojure style and have a large number of stores, the HOC would make a lot of sense.

A store contains a state object which is immutable, but not just that, all it's children, and children's children are immutable too. So more than just an atom I think.

This is what means re-rendering the root, by `store.subscribe(render)`,  or by `forceUpdate` of the root component, doesn't have to mean re-rendering the whole tree. If we have a pure component, it will only re-render if its props change (measured by shallow comparison). Say we have a root component, each with 10 children, each with 100 children, and some data used by one of the leaf component changes, only 3 components are re-rendered (the leaf, it's parent, and the root), rather than all 1,011. Also keep in mind "re-rendering" just means running the render function, the DOM is only updated if there're a change in the render output.

Of course, if each of those 1,000 leaf components had its own store you could make it just one render.

There are definitely some valid uses for multiple stores.

**Comment by shivekkhurana** [comment]
Closing this for now. I'll try two approaches : 
- multiple stores (pure-store behaves like clojure atom)
- single store with Immutable.js (immutable maps behaves like clojure atoms)

and update here if I find something. 

While researching, I found [this video](https://www.youtube.com/watch?v=VJ38wSFbM3A) where @gearon talks about react-redux connect's optimisations. Might be helpful.
